import { GoogleGenAI } from "@google/genai";

// Helper to convert File to Base64 data for SDK
const fileToInlineData = async (file: File): Promise<{ data: string; mimeType: string }> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      // Extract the base64 data part (remove "data:image/jpeg;base64,")
      const base64Data = base64String.split(',')[1];
      resolve({
        data: base64Data,
        mimeType: file.type,
      });
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

// Plant ID Service
export const identifyPlantsInImage = async (
  imageBlobUrl: string
): Promise<string[]> => {
  try {
    const apiKey = process.env.API_KEY;
    if (!apiKey) return [];

    const ai = new GoogleGenAI({ apiKey });

    // Convert blob URL to base64 if needed
    // For simplicity in this demo, we assume imageBlobUrl is a data URL (base64)
    const base64Data = imageBlobUrl.split(',')[1];

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash', // Using 2.5 Flash for reasoning
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/png', // simplified assumption
            },
          },
          {
            text: "Identify the 5 most prominent plant types in this image (e.g. 'Palm', 'Fern', 'Gum Tree'). Return ONLY a JSON array of strings.",
          },
        ],
      },
      config: {
        responseMimeType: "application/json"
      }
    });

    const text = response.text;
    if (!text) return [];
    
    return JSON.parse(text);
  } catch (e) {
    console.error("Plant ID failed", e);
    return [];
  }
};

export const generateLandscapeDesign = async (
  imageInput: File | string,
  prompt: string,
  isBushfireZone?: boolean
): Promise<string> => {
  try {
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      throw new Error("API Key is missing. Please check your environment configuration.");
    }

    const ai = new GoogleGenAI({ apiKey });

    let imageData = '';
    let mimeType = 'image/png';

    // Handle Input Type (File vs Base64 String)
    if (typeof imageInput === 'string') {
        // Assume Base64 Data URL
        const matches = imageInput.match(/^data:(.+);base64,(.+)$/);
        if (matches && matches.length === 3) {
            mimeType = matches[1];
            imageData = matches[2];
        } else {
             throw new Error("Invalid image format for evolution.");
        }
    } else {
        // Handle File object
        const result = await fileToInlineData(imageInput);
        imageData = result.data;
        mimeType = result.mimeType;
    }

    // Construct the specialized prompt
    // SIMPLIFIED PROMPT: Direct instructions prevent the model from entering "chat" mode and returning text.
    let enhancedPrompt = `Edit this image. Transform the landscape. 
    ${prompt}
    Output a photorealistic image. Maintain original lighting and perspective.`;
    
    if (isBushfireZone) {
      enhancedPrompt += ` Use fire-retardant plants, gravel paths, and non-flammable materials.`;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: imageData,
              mimeType: mimeType,
            },
          },
          {
            text: enhancedPrompt,
          },
        ],
      },
    });

    // Iterate through parts to find the image
    const parts = response.candidates?.[0]?.content?.parts;
    if (!parts) {
      throw new Error("No content generated by AI model");
    }

    let resultImage = null;

    for (const part of parts) {
      if (part.inlineData) {
        const base64EncodeString = part.inlineData.data;
        const responseMimeType = part.inlineData.mimeType || 'image/png';
        resultImage = `data:${responseMimeType};base64,${base64EncodeString}`;
        break;
      }
    }

    if (!resultImage) {
       // Check if model returned text error/explanation instead
       const textPart = parts.find(p => p.text);
       if (textPart) {
         console.warn("Model returned text:", textPart.text);
         throw new Error("The model could not generate an image based on these instructions.");
       }
       throw new Error("No image generated in response");
    }

    return resultImage;

  } catch (error) {
    console.error("Generation Service Error:", error);
    throw error;
  }
};