import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';

dotenv.config();

const app = express();
// Cloud Run (and most PaaS) injects the PORT environment variable (usually 8080).
// We must listen on this port for the container to start successfully.
const PORT = process.env.PORT || 3001;

// Increase payload limit to handle base64 images
app.use(express.json({ limit: '50mb' }));
app.use(cors());

// Health Check Endpoint for Cloud Run
app.get('/health', (req, res) => {
  res.status(200).send('OK');
});

// Root endpoint to ensure container doesn't look like it's crashing on 404s during startup probes
app.get('/', (req, res) => {
  res.send('OnThyme Landscapes Visualiser API is running');
});

app.post('/api/generate', async (req, res) => {
  try {
    const { image, mimeType, prompt } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      console.error("API Key missing");
      return res.status(500).json({ error: "Server configuration error: API Key missing" });
    }

    const ai = new GoogleGenAI({ apiKey });

    // Construct the specialized prompt on the server side
    const enhancedPrompt = `
      Act as a professional landscape architect for "OnThymeLandscapes" in Australia. 
      Edit the provided image to transform the outdoor space according to the user's request.
      Maintain a photorealistic style. 
      User Request: ${prompt}.
      
      Ensure the lighting and perspective match the original photo perfectly.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: image,
              mimeType: mimeType || 'image/png',
            },
          },
          {
            text: enhancedPrompt,
          },
        ],
      },
    });

    // Iterate through parts to find the image
    const parts = response.candidates?.[0]?.content?.parts;
    if (!parts) {
      throw new Error("No content generated by AI model");
    }

    let resultImage = null;

    for (const part of parts) {
      if (part.inlineData) {
        const base64EncodeString = part.inlineData.data;
        const responseMimeType = part.inlineData.mimeType || 'image/png';
        resultImage = `data:${responseMimeType};base64,${base64EncodeString}`;
        break;
      }
    }

    if (!resultImage) {
      throw new Error("No image generated in response");
    }

    res.json({ result: resultImage });

  } catch (error) {
    console.error("Backend Generation Error:", error);
    res.status(500).json({ error: error.message || "Failed to generate design" });
  }
});

// BIND TO 0.0.0.0 IS CRITICAL FOR CLOUD RUN
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Proxy server running on port ${PORT}`);
});